import { useEffect, useState } from 'react';
import { api, type Campaign, type Lead, type Deal } from '../../api';
import { apiEvents } from '../../api';
import { Plus, Search, Filter, RefreshCw, Megaphone, DollarSign, Percent, TrendingUp } from 'lucide-react';

export default function CampaignsPage() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [leads, setLeads] = useState<Lead[]>([]);
  const [deals, setDeals] = useState<Deal[]>([]);
  const [loading, setLoading] = useState(true);

  // Search & Filter state
  const [searchTerm, setSearchTerm] = useState('');
  const [typeFilter, setTypeFilter] = useState('All');
  const [statusFilter, setStatusFilter] = useState('All');
  const [currentPage, setCurrentPage] = useState(1);
  const campaignsPerPage = 8;

  // Create Modal state
  const [showModal, setShowModal] = useState(false);
  const [newCampaign, setNewCampaign] = useState({
    campaign_name: '',
    campaign_type: 'Email' as any,
    status: 'Planning' as any,
    budget: '',
    actual_cost: '',
    expected_revenue: '',
    description: ''
  });

  const fetchData = async () => {
    try {
      setLoading(true);
      const [campaignsData, leadsData, dealsData] = await Promise.all([
        api.getCampaigns(),
        api.getLeads(),
        api.getDeals()
      ]);
      setCampaigns(campaignsData);
      setLeads(leadsData);
      setDeals(dealsData);
    } catch (err) {
      console.error('Error fetching campaigns workspace data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
    return apiEvents.subscribe(() => {
      fetchData();
    });
  }, []);

  // Compute metrics for each campaign
  const getCampaignMetrics = (campaign: Campaign) => {
    // Find leads generated by this campaign
    const campaignLeads = leads.filter(l => l.campaign_id === campaign.campaign_id);
    const leadsCount = campaignLeads.length;

    // Find won deals linked to these leads
    const campaignDeals = deals.filter(d => campaignLeads.some(l => l.lead_id === d.lead_id));
    const wonDeals = campaignDeals.filter(d => d.deal_status === 'Won');
    const totalRevenue = wonDeals.reduce((sum, d) => sum + d.deal_value, 0);

    // ROI = ((Revenue - Cost) / Cost) * 100
    const cost = campaign.actual_cost || 1; // avoid division by zero
    const roi = ((totalRevenue - campaign.actual_cost) / cost) * 100;

    return {
      leadsCount,
      totalRevenue,
      roi: campaign.actual_cost > 0 ? roi : 0
    };
  };

  const handleCreateCampaign = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const dataToSubmit = {
        ...newCampaign,
        budget: parseFloat(newCampaign.budget) || 0,
        actual_cost: parseFloat(newCampaign.actual_cost) || 0,
        expected_revenue: parseFloat(newCampaign.expected_revenue) || 0
      };

      await api.createCampaign(dataToSubmit);
      setShowModal(false);
      setNewCampaign({
        campaign_name: '',
        campaign_type: 'Email',
        status: 'Planning',
        budget: '',
        actual_cost: '',
        expected_revenue: '',
        description: ''
      });
    } catch (err) {
      console.error('Error creating campaign:', err);
    }
  };

  const getStatusBadgeClass = (status: string) => {
    switch (status) {
      case 'Planning': return 'badge-status-new';
      case 'Active': return 'badge-status-qualified';
      case 'Completed': return 'badge-status-converted';
      case 'Cancelled': return 'badge-status-disqualified';
      default: return '';
    }
  };

  // Filter and Search logic
  const filteredCampaigns = campaigns.filter(c => {
    const matchesSearch = c.campaign_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      c.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = typeFilter === 'All' || c.campaign_type === typeFilter;
    const matchesStatus = statusFilter === 'All' || c.status === statusFilter;
    return matchesSearch && matchesType && matchesStatus;
  });

  // Pagination calculations
  const totalPages = Math.ceil(filteredCampaigns.length / campaignsPerPage) || 1;
  const indexOfLastCamp = currentPage * campaignsPerPage;
  const indexOfFirstCamp = indexOfLastCamp - campaignsPerPage;
  const currentCampaigns = filteredCampaigns.slice(indexOfFirstCamp, indexOfLastCamp);

  // Summary Card Metrics
  const activeCampaignsCount = campaigns.filter(c => c.status === 'Active').length;
  const totalBudget = campaigns.reduce((sum, c) => sum + c.budget, 0);
  const totalCost = campaigns.reduce((sum, c) => sum + c.actual_cost, 0);
  
  // Overall Won Revenue & ROI
  const wonDealsTotal = deals.filter(d => d.deal_status === 'Won').reduce((sum, d) => sum + d.deal_value, 0);
  const overallROI = totalCost > 0 ? ((wonDealsTotal - totalCost) / totalCost) * 100 : 0;

  return (
    <div className="campaigns-workspace animate-fade-in" style={{ paddingBottom: '40px' }}>
      
      {/* Header controls */}
      <div className="action-bar-top" style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '24px',
        flexWrap: 'wrap',
        gap: '16px'
      }}>
        <div>
          <h2 style={{ fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)' }}>Campaigns & Marketing</h2>
          <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Plan, execute and measure marketing ROI</span>
        </div>
        
        <button className="btn btn-primary" onClick={() => setShowModal(true)}>
          <Plus className="w-4 h-4" />
          <span>Create Campaign</span>
        </button>
      </div>

      {/* Metrics Row */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '20px',
        marginBottom: '24px'
      }}>
        {/* Active Campaigns */}
        <div className="card">
          <div className="card-body" style={{ display: 'flex', alignItems: 'center', gap: '16px', padding: '20px' }}>
            <div style={{
              width: '44px',
              height: '44px',
              borderRadius: '50%',
              backgroundColor: 'rgba(59, 130, 246, 0.1)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#3b82f6'
            }}>
              <Megaphone className="w-5 h-5" />
            </div>
            <div>
              <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block' }}>Active Campaigns</span>
              <span style={{ fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)' }}>{activeCampaignsCount}</span>
            </div>
          </div>
        </div>

        {/* Total Budget */}
        <div className="card">
          <div className="card-body" style={{ display: 'flex', alignItems: 'center', gap: '16px', padding: '20px' }}>
            <div style={{
              width: '44px',
              height: '44px',
              borderRadius: '50%',
              backgroundColor: 'rgba(16, 185, 129, 0.1)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#10b981'
            }}>
              <DollarSign className="w-5 h-5" />
            </div>
            <div>
              <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block' }}>Total Allocated Budget</span>
              <span style={{ fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)' }}>
                {new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(totalBudget)}
              </span>
            </div>
          </div>
        </div>

        {/* Total Cost */}
        <div className="card">
          <div className="card-body" style={{ display: 'flex', alignItems: 'center', gap: '16px', padding: '20px' }}>
            <div style={{
              width: '44px',
              height: '44px',
              borderRadius: '50%',
              backgroundColor: 'rgba(245, 158, 11, 0.1)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#f59e0b'
            }}>
              <TrendingUp className="w-5 h-5" />
            </div>
            <div>
              <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block' }}>Total Cost Incurred</span>
              <span style={{ fontSize: '20px', fontWeight: 700, color: 'var(--text-primary)' }}>
                {new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(totalCost)}
              </span>
            </div>
          </div>
        </div>

        {/* ROI gauge */}
        <div className="card">
          <div className="card-body" style={{ display: 'flex', alignItems: 'center', gap: '16px', padding: '20px' }}>
            <div style={{
              width: '44px',
              height: '44px',
              borderRadius: '50%',
              backgroundColor: 'rgba(139, 92, 246, 0.1)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#8b5cf6'
            }}>
              <Percent className="w-5 h-5" />
            </div>
            <div>
              <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block' }}>Overall Won Return (ROI)</span>
              <span style={{ fontSize: '20px', fontWeight: 700, color: overallROI >= 0 ? '#10b981' : '#ef4444' }}>
                {overallROI.toFixed(1)}%
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Filter and Search controls */}
      <div className="card" style={{ marginBottom: '20px' }}>
        <div className="card-body" style={{ padding: '16px 20px' }}>
          <div style={{
            display: 'flex',
            gap: '16px',
            alignItems: 'center',
            flexWrap: 'wrap'
          }}>
            {/* Search Input */}
            <div style={{ position: 'relative', flex: 1, minWidth: '240px' }}>
              <Search className="w-4 h-4 text-slate-400" style={{
                position: 'absolute',
                left: '12px',
                top: '50%',
                transform: 'translateY(-50%)'
              }} />
              <input
                type="text"
                placeholder="Search campaigns by name or description..."
                value={searchTerm}
                onChange={e => { setSearchTerm(e.target.value); setCurrentPage(1); }}
                style={{
                  width: '100%',
                  height: '38px',
                  paddingLeft: '38px',
                  border: '1px solid var(--border-color)',
                  borderRadius: 'var(--radius-md)',
                  backgroundColor: 'var(--bg-main)',
                  fontSize: '13.5px'
                }}
              />
            </div>

            {/* Type Filter */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Filter className="w-4 h-4 text-slate-400" />
              <select
                value={typeFilter}
                onChange={e => { setTypeFilter(e.target.value); setCurrentPage(1); }}
                style={{
                  height: '38px',
                  padding: '0 12px',
                  border: '1px solid var(--border-color)',
                  borderRadius: 'var(--radius-md)',
                  backgroundColor: 'white',
                  fontSize: '13.5px'
                }}
              >
                <option value="All">All Types</option>
                <option value="Email">Email</option>
                <option value="Webinar">Webinar</option>
                <option value="Social">Social</option>
                <option value="SEO">SEO</option>
                <option value="Referral">Referral</option>
                <option value="Other">Other</option>
              </select>
            </div>

            {/* Status Filter */}
            <div>
              <select
                value={statusFilter}
                onChange={e => { setStatusFilter(e.target.value); setCurrentPage(1); }}
                style={{
                  height: '38px',
                  padding: '0 12px',
                  border: '1px solid var(--border-color)',
                  borderRadius: 'var(--radius-md)',
                  backgroundColor: 'white',
                  fontSize: '13.5px'
                }}
              >
                <option value="All">All Statuses</option>
                <option value="Planning">Planning</option>
                <option value="Active">Active</option>
                <option value="Completed">Completed</option>
                <option value="Cancelled">Cancelled</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Main Table view */}
      {loading ? (
        <div className="card" style={{ padding: '40px', textAlign: 'center' }}>
          <RefreshCw className="w-6 h-6 animate-spin text-blue-600 inline-block mb-2" />
          <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>Fetching campaigns list...</p>
        </div>
      ) : filteredCampaigns.length === 0 ? (
        <div className="card" style={{ padding: '48px 24px', textAlign: 'center' }}>
          <p style={{ color: 'var(--text-secondary)', fontSize: '15px' }}>No campaigns matching the filters found.</p>
        </div>
      ) : (
        <div className="card" style={{ overflow: 'hidden' }}>
          <div className="table-wrapper">
            <table className="crm-table">
              <thead>
                <tr>
                  <th>Campaign Name</th>
                  <th>Type</th>
                  <th>Status</th>
                  <th>Budget</th>
                  <th>Actual Cost</th>
                  <th>Leads Created</th>
                  <th>Won Revenue</th>
                  <th>ROI</th>
                </tr>
              </thead>
              <tbody>
                {currentCampaigns.map(c => {
                  const m = getCampaignMetrics(c);
                  return (
                    <tr key={c.campaign_id} style={{ cursor: 'default' }}>
                      <td>
                        <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{c.campaign_name}</span>
                        {c.description && (
                          <span style={{ display: 'block', fontSize: '11.5px', color: 'var(--text-secondary)', marginTop: '2px' }}>
                            {c.description}
                          </span>
                        )}
                      </td>
                      <td>{c.campaign_type}</td>
                      <td>
                        <span className={`badge ${getStatusBadgeClass(c.status)}`}>
                          {c.status}
                        </span>
                      </td>
                      <td>
                        {new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(c.budget)}
                      </td>
                      <td>
                        {new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(c.actual_cost)}
                      </td>
                      <td style={{ fontWeight: 600, color: 'var(--text-primary)', textAlign: 'center' }}>
                        {m.leadsCount}
                      </td>
                      <td>
                        {new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(m.totalRevenue)}
                      </td>
                      <td style={{ fontWeight: 700, color: m.roi >= 0 ? '#10b981' : '#ef4444' }}>
                        {m.roi.toFixed(1)}%
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Pagination Row */}
          <div className="table-pagination">
            <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>
              Showing {indexOfFirstCamp + 1} to {Math.min(indexOfLastCamp, filteredCampaigns.length)} of {filteredCampaigns.length} campaigns
            </span>
            <div className="pagination-pages">
              <button 
                className="page-btn" 
                onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                disabled={currentPage === 1}
              >
                &lt;
              </button>
              {Array.from({ length: totalPages }, (_, i) => i + 1).map(p => (
                <button
                  key={p}
                  className={`page-btn ${currentPage === p ? 'active' : ''}`}
                  onClick={() => setCurrentPage(p)}
                >
                  {p}
                </button>
              ))}
              <button 
                className="page-btn" 
                onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                disabled={currentPage === totalPages}
              >
                &gt;
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Create Modal */}
      {showModal && (
        <div className="modal-overlay show" onClick={() => setShowModal(false)}>
          <div className="modal-container" onClick={e => e.stopPropagation()} style={{ maxWidth: '600px' }}>
            <div className="modal-header">
              <h3 style={{ fontSize: '16px', fontWeight: 700 }}>Launch New Marketing Campaign</h3>
              <button 
                onClick={() => setShowModal(false)}
                style={{ background: 'none', fontSize: '20px', cursor: 'pointer', color: 'var(--text-secondary)' }}
              >
                &times;
              </button>
            </div>
            
            <form onSubmit={handleCreateCampaign}>
              <div className="modal-body" style={{ padding: '24px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                  
                  {/* Campaign Name */}
                  <div className="form-group" style={{ gridColumn: 'span 2' }}>
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, marginBottom: '6px' }}>Campaign Name *</label>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="e.g. Q3 Partner Referral Program"
                      value={newCampaign.campaign_name}
                      onChange={e => setNewCampaign({ ...newCampaign, campaign_name: e.target.value })}
                      required
                      style={{ width: '100%', height: '38px', padding: '0 12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)' }}
                    />
                  </div>

                  {/* Campaign Type */}
                  <div className="form-group">
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, marginBottom: '6px' }}>Campaign Type</label>
                    <select
                      className="form-control"
                      value={newCampaign.campaign_type}
                      onChange={e => setNewCampaign({ ...newCampaign, campaign_type: e.target.value as any })}
                      style={{ width: '100%', height: '38px', padding: '0 12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)' }}
                    >
                      <option value="Email">Email</option>
                      <option value="Webinar">Webinar</option>
                      <option value="Social">Social</option>
                      <option value="SEO">SEO</option>
                      <option value="Referral">Referral</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>

                  {/* Campaign Status */}
                  <div className="form-group">
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, marginBottom: '6px' }}>Status</label>
                    <select
                      className="form-control"
                      value={newCampaign.status}
                      onChange={e => setNewCampaign({ ...newCampaign, status: e.target.value as any })}
                      style={{ width: '100%', height: '38px', padding: '0 12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)' }}
                    >
                      <option value="Planning">Planning</option>
                      <option value="Active">Active</option>
                      <option value="Completed">Completed</option>
                      <option value="Cancelled">Cancelled</option>
                    </select>
                  </div>

                  {/* Budget */}
                  <div className="form-group">
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, marginBottom: '6px' }}>Allocated Budget (INR) *</label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder="e.g. 50000"
                      value={newCampaign.budget}
                      onChange={e => setNewCampaign({ ...newCampaign, budget: e.target.value })}
                      required
                      style={{ width: '100%', height: '38px', padding: '0 12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)' }}
                    />
                  </div>

                  {/* Actual Cost */}
                  <div className="form-group">
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, marginBottom: '6px' }}>Actual Cost Incurred (INR)</label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder="e.g. 45000"
                      value={newCampaign.actual_cost}
                      onChange={e => setNewCampaign({ ...newCampaign, actual_cost: e.target.value })}
                      style={{ width: '100%', height: '38px', padding: '0 12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)' }}
                    />
                  </div>

                  {/* Expected Revenue */}
                  <div className="form-group" style={{ gridColumn: 'span 2' }}>
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, marginBottom: '6px' }}>Expected Sales Revenue (INR)</label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder="e.g. 200000"
                      value={newCampaign.expected_revenue}
                      onChange={e => setNewCampaign({ ...newCampaign, expected_revenue: e.target.value })}
                      style={{ width: '100%', height: '38px', padding: '0 12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)' }}
                    />
                  </div>

                  {/* Description */}
                  <div className="form-group" style={{ gridColumn: 'span 2' }}>
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, marginBottom: '6px' }}>Campaign Description</label>
                    <textarea
                      className="form-control"
                      rows={3}
                      placeholder="Brief notes about the target audience, channels used or campaign targets..."
                      value={newCampaign.description}
                      onChange={e => setNewCampaign({ ...newCampaign, description: e.target.value })}
                      style={{ width: '100%', padding: '12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)' }}
                    />
                  </div>

                </div>
              </div>
              
              <div className="modal-footer" style={{
                padding: '16px 28px',
                borderTop: '1px solid var(--border-color)',
                display: 'flex',
                justifyContent: 'flex-end',
                gap: '12px'
              }}>
                <button type="button" className="btn btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
                <button type="submit" className="btn btn-primary">Launch Campaign</button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
